// data
export const SAVE_SIGHTS = "SAVE_SIGHTS";
export const SAVE_WALKS = "SAVE_WALKS";
export const SAVE_CITIES = "SAVE_CITIES";
export const SAVE_BOARDS = "SAVE_BOARDS";
// registration
export const SET_FIRST_NAME = "SET_FIRST_NAME";
export const SET_LAST_NAME = "SET_LAST_NAME";
export const SET_REGISTRATION_EMAIL = "SET_REGISTRATION_EMAIL";
export const SET_REGISTRATION_PASSWORD = "SET_REGISTRATION_PASSWORD";
export const SET_ACTIVATION_MESSAGE_EMPHASIS =
  "SET_ACTIVATION_MESSAGE_EMPHASIS";
// login
export const SET_POPUP_VISIBLE = "SET_POPUP_VISIBLE";
export const SET_LOGGED_IN = "SET_LOGGED_IN";
export const SET_USER_ID = "SET_USER_ID";
export const SET_USER_FIRST_NAME = "SET_USER_FIRST_NAME";
export const SET_USER_LAST_NAME = "SET_USER_LAST_NAME";
export const SET_LOGIN_EMAIL = "SET_LOGIN_EMAIL";
export const SET_LOGIN_PASSWORD = "SET_LOGIN_PASSWORD";
export const SET_FORGOT_PASSWORD_EMAIL = "SET_FORGOT_PASSWORD_EMAIL";
// reset login credentials
export const SET_RESET_PASSWORD_EMAIL = "SET_RESET_PASSWORD_EMAIL";
export const SET_RESET_PASSWORD_OLD_PASSWORD =
  "SET_RESET_PASSWORD_OLD_PASSWORD";
export const SET_RESET_PASSWORD_NEW_PASSWORD =
  "SET_RESET_PASSWORD_NEW_PASSWORD";
export const SET_RESET_PASSWORD_CONFIRM_NEW_PASSWORD =
  "SET_RESET_PASSWORD_CONFIRM_NEW_PASSWORD";
// verification
export const SET_VERIFICATION_EMAIL = "SET_VERIFICATION_EMAIL";
// search
export const HANDLE_CHANGE_SEARCH = "HANDLE_CHANGE_SEARCH";
export const HANDLE_CLICK_SEARCH = "HANDLE_CLICK_SEARCH";
export const SET_REDIRECT = "SET_REDIRECT";
// recaptcha
export const SAVE_SITEKEY = "SAVE_SITEKEY";
